### ISSUE TITLE
Filter.OddMapCollectFlow test fails on Windows

### ISSUE THREAD

**Issue by FolMing** [3rdparty/stout-eventuals#48]
### Description:
Filter.OddMapCollectFlow test fails on Windows with the following error:
```
test/filter.cc(98): error: Expected equality of these values:
  *res.begin()
    Which is: 6
  18
test/filter.cc(99): error: Expected equality of these values:
  *++res.begin()
    Which is: 18
  6
```

### Steps to reproduce:
Run the test on Windows.

**Comment by onelxj** [comment]
I guess that the hashes for values are calculated in different ways

`unordered_map::insert(const_iterator hint, T value) `

where hint - just suggestion of the position, anyways the function can accept it or just calculate the hash and choose another position
